[2022-11-16T05:38:43.989+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: airflow_tutorial_v01._read_csv scheduled__2017-07-23T16:00:00+00:00 [queued]>
[2022-11-16T05:38:44.000+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: airflow_tutorial_v01._read_csv scheduled__2017-07-23T16:00:00+00:00 [queued]>
[2022-11-16T05:38:44.001+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-16T05:38:44.002+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-11-16T05:38:44.002+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-16T05:38:44.024+0000] {taskinstance.py:1383} INFO - Executing <Task(_PythonDecoratedOperator): _read_csv> on 2017-07-23 16:00:00+00:00
[2022-11-16T05:38:44.029+0000] {standard_task_runner.py:54} INFO - Started process 1189 to run task
[2022-11-16T05:38:44.037+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', '***_tutorial_v01', '_read_csv', 'scheduled__2017-07-23T16:00:00+00:00', '--job-id', '193', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpm6zlxclr']
[2022-11-16T05:38:44.039+0000] {standard_task_runner.py:83} INFO - Job 193: Subtask _read_csv
[2022-11-16T05:38:44.041+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/test.py
[2022-11-16T05:38:45.172+0000] {task_command.py:384} INFO - Running <TaskInstance: airflow_tutorial_v01._read_csv scheduled__2017-07-23T16:00:00+00:00 [running]> on host fe2268fd6bfb
[2022-11-16T05:38:45.460+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=***_tutorial_v01
AIRFLOW_CTX_TASK_ID=_read_csv
AIRFLOW_CTX_EXECUTION_DATE=2017-07-23T16:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2017-07-23T16:00:00+00:00
[2022-11-16T05:38:45.466+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 188, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 45, in _read_csv
    '/Users/gabestechschulte/Documents/repos/books-with-code/bmcp/data/babies.csv'
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/Users/gabestechschulte/Documents/repos/books-with-code/bmcp/data/babies.csv'
[2022-11-16T05:38:45.507+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=***_tutorial_v01, task_id=_read_csv, execution_date=20170723T160000, start_date=20221116T053843, end_date=20221116T053845
[2022-11-16T05:38:45.553+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 193 for task _read_csv ([Errno 2] No such file or directory: '/Users/gabestechschulte/Documents/repos/books-with-code/bmcp/data/babies.csv'; 1189)
[2022-11-16T05:38:45.708+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-16T05:38:45.830+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
