[2022-11-16T05:28:11.760+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: airflow_tutorial_v01._read_csv scheduled__2017-06-11T16:00:00+00:00 [queued]>
[2022-11-16T05:28:11.782+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: airflow_tutorial_v01._read_csv scheduled__2017-06-11T16:00:00+00:00 [queued]>
[2022-11-16T05:28:11.783+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-16T05:28:11.783+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-11-16T05:28:11.784+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-16T05:28:11.806+0000] {taskinstance.py:1383} INFO - Executing <Task(_PythonDecoratedOperator): _read_csv> on 2017-06-11 16:00:00+00:00
[2022-11-16T05:28:11.811+0000] {standard_task_runner.py:54} INFO - Started process 518 to run task
[2022-11-16T05:28:11.817+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', '***_tutorial_v01', '_read_csv', 'scheduled__2017-06-11T16:00:00+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpyii2rvhh']
[2022-11-16T05:28:11.818+0000] {standard_task_runner.py:83} INFO - Job 85: Subtask _read_csv
[2022-11-16T05:28:11.822+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/test.py
[2022-11-16T05:28:12.137+0000] {task_command.py:384} INFO - Running <TaskInstance: airflow_tutorial_v01._read_csv scheduled__2017-06-11T16:00:00+00:00 [running]> on host fe2268fd6bfb
[2022-11-16T05:28:12.225+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=***_tutorial_v01
AIRFLOW_CTX_TASK_ID=_read_csv
AIRFLOW_CTX_EXECUTION_DATE=2017-06-11T16:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2017-06-11T16:00:00+00:00
[2022-11-16T05:28:12.229+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 188, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 45, in _read_csv
    '/Users/gabestechschulte/Documents/repos/books-with-code/bmcp/data/babies.csv'
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/Users/gabestechschulte/Documents/repos/books-with-code/bmcp/data/babies.csv'
[2022-11-16T05:28:12.241+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=***_tutorial_v01, task_id=_read_csv, execution_date=20170611T160000, start_date=20221116T052811, end_date=20221116T052812
[2022-11-16T05:28:12.255+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 85 for task _read_csv ([Errno 2] No such file or directory: '/Users/gabestechschulte/Documents/repos/books-with-code/bmcp/data/babies.csv'; 518)
[2022-11-16T05:28:12.319+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-16T05:28:12.335+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
